export default [
  {k: 'qualification', m: 'n.', i: '', g: 'qualification__gb_1', u: 'qualification__us_4', l: 'B1', e: ''}, 
  {k: 'qualified', m: 'adj.', i: '', g: 'qualified__gb_1', u: 'qualified__us_4', l: 'B1', e: ''}, 
  {k: 'qualify', m: 'v.', i: '', g: 'qualify__gb_1', u: 'qualify__us_1', l: 'B1', e: ''}, 
  {k: 'quality', m: 'n.', i: '', g: 'quality__gb_3', u: 'quality__us_2', l: 'A2', e: ''}, 
  {k: 'quantity', m: 'n.', i: '', g: 'quantity__gb_3', u: 'quantity__us_1', l: 'A2', e: ''}, 
  {k: 'quarter', m: 'n.', i: '', g: 'quarter__gb_1', u: 'quarter__us_3', l: 'A1', e: ''}, 
  {k: 'queen', m: 'n.', i: '', g: 'queen_1_gb_1', u: 'queen__us_1', l: 'A2', e: ''}, 
  {k: 'query', m: 'n.', i: '', g: 'query__gb_1', u: 'query__us_1_rr', l: 'C1', e: ''}, 
  {k: 'quest', m: 'n.', i: '', g: 'quest__gb_1', u: 'quest__us_1', l: 'C1', e: ''}, 
  {k: 'question', m: 'n.', i: '', g: 'question__gb_2', u: 'question__us_4', l: 'A1', e: ''}, 
  {k: 'question', m: 'v.', i: '', g: 'question__gb_2', u: 'question__us_4', l: 'A2', e: ''}, 
  {k: 'questionnaire', m: 'n.', i: '', g: 'questionnaire__gb_2', u: 'questionnaire__us_1', l: 'B2', e: ''}, 
  {k: 'queue', m: 'n.', i: '', g: 'queue__gb_1', u: 'queue__us_1', l: 'B1', e: ''}, 
  {k: 'queue', m: 'v.', i: '', g: 'queue__gb_1', u: 'queue__us_1', l: 'B1', e: ''}, 
  {k: 'quick', m: 'adj.', i: '', g: 'quick__gb_1', u: 'quick__us_1', l: 'A1', e: ''}, 
  {k: 'quickly', m: 'adv.', i: '', g: 'quickly__gb_1', u: 'quickly__us_3', l: 'A1', e: ''}, 
  {k: 'quiet', m: 'adj.', i: '', g: 'quiet__gb_2', u: 'quiet__us_1', l: 'A1', e: ''}, 
  {k: 'quietly', m: 'adv.', i: '', g: 'quietly__gb_1', u: 'quietly__us_3', l: 'A2', e: ''}, 
  {k: 'quit', m: 'v.', i: '', g: 'quit__gb_1', u: 'quit__us_1', l: 'B1', e: ''}, 
  {k: 'quite', m: 'adv.', i: '', g: 'quite__gb_1', u: 'quite__us_1', l: 'A1', e: ''}, 
  {k: 'quota', m: 'n.', i: '', g: 'quota__gb_1', u: 'quota__us_1', l: 'C1', e: ''}, 
  {k: 'quotation', m: 'n.', i: '', g: 'quotation__gb_2', u: 'quotation__us_2', l: 'B1', e: ''}, 
  {k: 'quote', m: 'n.', i: '', g: 'quote__gb_2', u: 'quote__us_1', l: 'B1', e: ''}, 
  {k: 'quote', m: 'v.', i: '', g: 'quote__gb_2', u: 'quote__us_1', l: 'B1', e: ''}, 
]