export default [
  {k: 'yard', m: 'n.', i: '', g: 'yard__gb_1', u: 'yard__us_1', l: 'B1', e: ''}, 
  {k: 'yeah', m: 'exclamation.', i: '', g: 'yeah__gb_1', u: 'yeah__us_1', l: 'A1', e: ''}, 
  {k: 'year', m: 'n.', i: '', g: 'year__gb_1', u: 'year__us_1', l: 'A1', e: ''}, 
  {k: 'yell', m: 'v.', i: '', g: 'yell__gb_1', u: 'yell__us_1', l: 'C1', e: ''}, 
  {k: 'yellow', m: 'adj.', i: '', g: 'yellow__gb_2', u: 'yellow__us_3', l: 'A1', e: ''}, 
  {k: 'yellow', m: 'n.', i: '', g: 'yellow__gb_2', u: 'yellow__us_3', l: 'A1', e: ''}, 
  {k: 'yes', m: 'exclamation.', i: '', g: 'yes__gb_2', u: 'yes__us_2', l: 'A1', e: ''}, 
  {k: 'yesterday', m: 'adv.', i: '', g: 'yesterday__gb_1', u: 'yesterday__us_1_rr', l: 'A1', e: ''}, 
  {k: 'yesterday', m: 'n.', i: '', g: 'yesterday__gb_1', u: 'yesterday__us_1_rr', l: 'A1', e: ''}, 
  {k: 'yet', m: 'adv.', i: '', g: 'yet__gb_1', u: 'yet__us_1', l: 'A2', e: ''}, 
  {k: 'yet', m: 'conj.', i: '', g: 'yet__gb_1', u: 'yet__us_1', l: 'B2', e: ''}, 
  {k: 'yield', m: 'n.', i: '', g: 'yield__gb_2', u: 'yield__us_1', l: 'C1', e: ''}, 
  {k: 'yield', m: 'v.', i: '', g: 'yield__gb_2', u: 'yield__us_1', l: 'C1', e: ''}, 
  {k: 'you', m: 'pron.', i: '', g: 'you__gb_1', u: 'you__us_1_rr', l: 'A1', e: ''}, 
  {k: 'young', m: 'adj.', i: '', g: 'young_1_gb_1', u: 'young__us_1', l: 'A1', e: ''}, 
  {k: 'young', m: 'n.', i: '', g: 'young_1_gb_1', u: 'young__us_1', l: 'B1', e: ''}, 
  {k: 'youngster', m: 'n.', i: '', g: 'youngster__gb_1', u: 'youngster__us_1', l: 'C1', e: ''}, 
  {k: 'your', m: 'determiner.', i: '', g: 'your__gb_1', u: 'your__us_3_rr', l: 'A1', e: ''}, 
  {k: 'yours', m: 'pron.', i: '', g: 'yours__gb_1', u: 'yours__us_2_rr', l: 'A2', e: ''}, 
  {k: 'yourself', m: 'pron.', i: '', g: 'yourself__gb_1', u: 'yourself__us_1', l: 'A1', e: ''}, 
  {k: 'youth', m: 'n.', i: '', g: 'youth__gb_1', u: 'youth__us_1', l: 'B1', e: ''}, 
]